all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=partum_artificium'
      username: partum
      password: a5bab6b8e4b472fd884103be6c7482198261656dc40a891c1b5fa64db7b392c4
